version: "3"

x-common-variables: &common-variables
  DB_USERNAME: $DB_USERNAME
  DB_PASSWORD: $DB_PASSWORD
  DB_NAME: $DB_NAME
  DB_PORT: $DB_PORT
  DB_DOCKER_SERVICE_NAME: $DB_DOCKER_SERVICE_NAME

services:
  frontend:
    container_name: hsl-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - my-network

  # TODO: change target:production, NODE_ENV: production when deploying
  backend:
    container_name: hsl-backend
    # target is used to build a specific stage of ./server/Dockerfile
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    restart:
      unless-stopped
      # environment variables
    environment:
      NODE_ENV: development
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
      DB_DOCKER_SERVICE_NAME: $DB_DOCKER_SERVICE_NAME
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - my-network

  postgres:
    image: postgres:latest
    container_name: hsl-postgres
    restart: always
    environment:
      <<: *common-variables
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - hsldata:/var/lib/postgresql/data
    networks:
      - my-network

  nginx:
    container_name: hsl-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    restart: always
    # The app is working in the localhost:8008.
    ports:
      - "8008:80"
    networks:
      - my-network

volumes:
  hsldata:

networks:
  my-network:
