name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull source code and run Docker container
        run: |
          cd
          cd Documents/dingding
          git pull
          echo "#####Stopping containers#####"
          CONTAINERS=$(docker ps -a -q)
          if [ -n "$CONTAINERS" ]; then
            docker stop $CONTAINERS
            docker rm $CONTAINERS
            docker rmi $(docker images -q)
          else
            echo "No containers to stop"
          fi    
          docker compose up --build -d
